language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
    - android-sdk-license-.+

before_install:
  - chmod +x gradlew

script: ./gradlew assembleDebug